DROP TABLE IF EXISTS imdb_5000;
CREATE TABLE imdb_5000 (
  title text, 
  budget int,
  homepage text,
  original_language text, 
  overview text, 
  popularity real,
  release_date date, 
  revenue int, 
  runtime int, 
  tagline text, 
  vote_average real, 
  vote_count int,
  genre1 text, 
  genre2 text, 
  genre3 text, 
  keywords text, 
  production_company text, 
  production_countries text, 
  spoken_languages text, 
  director text, 
  character1name1 text, 
  character2name2 text, 
  character3name3 text, 
  character4name4 text, 
  character5name5 text, 
  character6name6 text, 
  character7name7 text, 
  character8name8 text, 
  character9name9 text, 
  character10name10 text
  
);
