DROP TABLE IF EXISTS moviesdata;
CREATE TABLE imbd_5000 (
  title text, 
  budget int,
  homepage text,
  original_language text, 
  overview text, 
  popularity real,
  release_date date, 
  revenue int, 
  runtime int, 
  tagline text, 
  vote_average real, 
  vote_count int,
  genre1 text, 
  genre2 text, 
  genre3 text, 
  keywords text, 
  production_company text, 
  production_countries text, 
  spoken_languages text, 
  director text, 
  character1:name1 text, 
  character2:name2 text, 
  character3:name3 text, 
  character4:name4 text, 
  character5:name5 text, 
  character6:name6 text, 
  character7:name7 text, 
  character8:name8 text, 
  character9:name9 text, 
  character10:name10 text
  
);